

export const metadata: Metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by next.js and Sanity.io',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
  {children}
      </body>
    </html>
  )
}
