import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by next.js and Sanity.io',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen max-w-5xl mx-auto'>
        <header className='flex items-center justify-between mt-10'>
          <Link href='/' className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold'>Onelio</Link>
        </header>
        <main className='py-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
